services:
  embycleaner:
    container_name: embyclean
    build: .
    image: okhao/emby_cleaner:latest
    ports:
      - "19898:19898"
    volumes:
      - /vol1/1000/Docker/embyclean/templates:/app/templates
      - /vol1/1000/Docker/embyclean/app.py:/app/app.py
      - /vol1/1000/Docker/embyclean/data:/app/data
    restart: always
